services:
  weaviate:
    image: semitechnologies/weaviate:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ~/weaviate_data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama'
      TEXT2VEC_OLLAMA_OllamaURL: 'http://host.docker.internal:11434'
      TEXT2VEC_OLLAMA_Model: 'qwen2.5:7b'
      CLUSTER_HOSTNAME: 'weaviate1'

