services:
  lightrag:
    container_name: lightrag_memory
    image: ghcr.io/suchanek/lightrag_pagent:latest
    ports:
      - "${PORT:-9622}:9621"
    volumes:
      - "${DATA_DIR}/${STORAGE_BACKEND}/${USER_ID}/memory_rag_storage:/app/data/rag_storage"
      - "${DATA_DIR}/${STORAGE_BACKEND}/${USER_ID}/memory_inputs:/app/data/inputs"
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
