services:
  lightrag:
    container_name: lightrag_memory
    image: ghcr.io/suchanek/lightrag_pagent:latest
    env_file:
      - .env
    ports:
      - "${LIGHTRAG_MEMORY_PORT:-9623}:9621"
    volumes:
      - "${AGNO_STORAGE_DIR}/memory_rag_storage:/app/data/rag_storage"
      - "${AGNO_STORAGE_DIR}/memory_inputs:/app/data/inputs"
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    environment:
      - USER_ID=Eric
      - WORKERS=1
      - MAX_PARALLEL_INSERT=1
      - PORT=9623
      # Explicit timeout settings for the container
      - HTTPX_TIMEOUT=7200
      - HTTPX_CONNECT_TIMEOUT=600
      - HTTPX_READ_TIMEOUT=7200
      - HTTPX_WRITE_TIMEOUT=600
      - HTTPX_POOL_TIMEOUT=600
      - OLLAMA_TIMEOUT=7200
      - OLLAMA_KEEP_ALIVE=3600
      - OLLAMA_NUM_PREDICT=16384
      - OLLAMA_TEMPERATURE=0.1
      - PDF_CHUNK_SIZE=1024
      - LLM_TIMEOUT=7200
      - EMBEDDING_TIMEOUT=3600
      - OLLAMA_REQUEST_TIMEOUT=14400
      - REQUESTS_TIMEOUT=14400
      - URLLIB3_TIMEOUT=14400
      - AIOHTTP_TIMEOUT=14400
      - SOCKET_TIMEOUT=14400
      - TCP_KEEPALIVE=true
      - TCP_KEEPALIVE_IDLE=600
      - TCP_KEEPALIVE_INTERVAL=60
      - TCP_KEEPALIVE_COUNT=9


    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9621/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
