services:
  lightrag:
    container_name: lightrag_memory
    image: ghcr.io/suchanek/lightrag_pagent:latest
    env_file:
      - env.server
    ports:
      - 9622:9621
    volumes:
      - "${AGNO_STORAGE_DIR}/memory_rag_storage:/app/data/rag_storage"
      - "${AGNO_STORAGE_DIR}/memory_inputs:/app/data/inputs"
      - ./env.server:/app/.env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9621/health')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "8g"
        
