services:
  lightrag:
    container_name: lightrag_memory
    image: ghcr.io/suchanek/lightrag_pagent:latest
    ports:
      - "${PORT:-9622}:9621"
    volumes:
      - ${DATA_DIR}/agno/${USER_ID}/memory_rag_storage:/app/data/rag_storage
      - ${DATA_DIR}/agno/${USER_ID}/memory_inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      # These variables are now sourced from the .env file via `env_file`.
      # This makes .env the single source of truth and avoids hardcoding.
      - LLM_BINDING_HOST=${OLLAMA_DOCKER_URL:-http://host.docker.internal:11434}
      - EMBEDDING_BINDING_HOST=${OLLAMA_DOCKER_URL:-http://host.docker.internal:11434}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
