[project]
name = "personalagent-service"
version = "0.1.0"
description = "PersonalAgent API/service (FastAPI + workers)"
requires-python = ">=3.11"
license = { text = "MIT" }
readme = "README.md"
authors = [{ name = "PersonalAgent System" }]

dependencies = [
    "fastapi>=0.114",
    "uvicorn[standard]>=0.30",
    "pydantic>=2.7",
    "httpx>=0.27",
    "websockets>=12.0",
    "loguru>=0.7",
    "rich>=13.7",
    "typer>=0.12",
    "uvloop>=0.19; platform_system != 'Windows'",
    "orjson>=3.10",
    "python-dotenv>=1.0",
    "tenacity>=9.0",
    "sse-starlette>=2.0",
    "aiofiles>=23.0",
    "watchdog>=4.0",
    "lancedb>=0.7",
    "openai>=1.44",
    "anthropic>=0.34",
    "ollama>=0.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "pytest-asyncio>=0.23",
    "ruff>=0.6",
    "black>=24.8",
    "mypy>=1.11",
    "types-requests",
]
server = [
    "gunicorn>=22.0",
]

[project.scripts]
pa-api = "personalagent.app.main:run"
pa-worker = "personalagent.worker.main:run"

[tool.uv]
python-preference = "only-managed"
python = "3.11"

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
