[project]
name = "pa-sd"
version = "0.1.0"
description = "Stable Diffusion runner for PersonalAgent (uv/CLI)"
requires-python = ">=3.11"
license = { text = "MIT" }
readme = "README.md"
authors = [{ name = "PersonalAgent System" }]

dependencies = [
    "torch==2.9.0",
    "diffusers==0.35.2",
    "transformers==4.45.1",
    "accelerate==0.34.2",
    "safetensors==0.4.5",
    "pillow==12.0.0",
    "opencv-python==4.12.0.88",
    "pandas==2.3.3",
    "tqdm==4.67.1",
    "matplotlib==3.10.7",
    "exif==1.6.1",
]

[project.scripts]
pa-txt2img = "txt2img:main"

[tool.uv]
# Lock Python to 3.11 for deterministic runs
python-preference = "only-managed"
python = "3.11"

[tool.uv.workspace]
members = []
